### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by ShenRuiLi** [thu-coai/KdConv#18]
02/21/2022 15:34:22 - INFO - __main__ -   ***** Running training *****
02/21/2022 15:34:22 - INFO - __main__ -     Num post-response pairs = 27550
02/21/2022 15:34:22 - INFO - __main__ -     Batch size = 8
02/21/2022 15:34:22 - INFO - __main__ -     Num steps = 10331
Epoch:   0%|          | 0/3 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:/Users/25687/Desktop/NLP_Paper/KdConv-master/benchmark/bertret/run_BERTRetrieval.py", line 384, in <module>
    main()
  File "C:/Users/25687/Desktop/NLP_Paper/KdConv-master/benchmark/bertret/run_BERTRetrieval.py", line 255, in main
    data = dataManager.get_next_batch(key='train')
  File "D:\Anaconda\envs\KdConv-master\lib\site-packages\cotk\dataloader\dataloader.py", line 195, in get_next_batch
    res = self.get_batch(key, index)
  File "C:\Users\25687\Desktop\NLP_Paper\KdConv-master\benchmark\bertret\myCoTK\dataloader\bert_dataloader.py", line 163, in get_batch
    resp_distractors_bert = self.data[key]['resp_distractors_bert'][idx]
IndexError: list index out of range
train set restart, 3443 batches and 6 left
在windows上跑bertret代码时出现了这个问题，一直说索引超出界限，请问怎么解决呢？

**Comment by chujiezheng** [comment]
可以先打印一下len(self.data[key]['resp_distractors_bert'])和idx看看

**Comment by ShenRuiLi** [comment]
![image](https://user-images.githubusercontent.com/74346622/154910838-aa2f4bd7-2e10-4d3d-8aa3-4f3dd5a7f97a.png)

**Comment by chujiezheng** [comment]
idx理应不会超。你改了其他地方的代码了吗？

**Comment by ShenRuiLi** [comment]
其他地方的代码没有改动。我看idx的值都很大，是一些文件的原因导致的吗？
![image](https://user-images.githubusercontent.com/74346622/154915049-b9941ef0-aac7-4148-ba4a-92cb787d62ca.png)

**Comment by chujiezheng** [comment]
我这儿没有同样的环境，不太好复现。可以把distractor文件删掉，重新跑一下看看

**Comment by chujiezheng** [comment]
python版本如果很高（比如3.8、3.9），也可以替换成3.5或3.6试试

**Comment by ShenRuiLi** [comment]
好的，谢谢您

**Comment by ShenRuiLi** [comment]
不好意思，是我改了一些代码导致的问题，抱歉打扰你了
