### ISSUE TITLE
请问TypeError: missing a required argument: 'file_id'这个问题可以解决吗？

### ISSUE THREAD

**Issue by xuhc12** [thu-coai/KdConv#7]
Traceback (most recent call last):
  File "/home/xhc/xuhc/KdConv-master/benchmark/seq2seq/run.py", line 84, in <module>
    run(*sys.argv[1:])
  File "/home/xhc/xuhc/KdConv-master/benchmark/seq2seq/run.py", line 80, in run
    main(args)
  File "/home/xhc/xuhc/KdConv-master/benchmark/seq2seq/main.py", line 61, in main
    data = try_cache(data_class, (args.datapath,), args.cache_dir)
  File "/home/xhc/xuhc/KdConv-master/benchmark/seq2seq/utils/cache_helper.py", line 21, in try_cache
    obj = module(*args)
  File "/home/xhc/xuhc/KdConv-master/benchmark/seq2seq/myCoTK/dataloader/single_turn_dialog.py", line 192, in __init__
    super(MySeq2Seq, self).__init__()
  File "/home/xhc/anaconda3/envs/xhc/lib/python3.6/site-packages/cotk/_utils/hooks.py", line 49, in wrapped
    bound = sign.bind(*args, **kwargs)
  File "/home/xhc/anaconda3/envs/xhc/lib/python3.6/inspect.py", line 2997, in bind
    return args[0]._bind(args[1:], kwargs)
  File "/home/xhc/anaconda3/envs/xhc/lib/python3.6/inspect.py", line 2912, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'file_id'
INFO: local path: ../data/film
INFO: processor type: Default

Process finished with exit code 1

**Comment by HarborZeng** [comment]
这个仓库感觉已经没人管了，你这个是 cotk 的版本问题，要用老版本，而且也不一定能成功的样子，`pip install cotk==0.0.1`

**Comment by chujiezheng** [comment]
抱歉先前忘记回复。这应该是你的文件输入路径错误，`file_id` 是数据文件夹的路径，里面应该包含`train.json`、`dev.json`和`test.json`三个文件。另外 cotk 也需要用老版本，`pip install cotk==0.0.1`
